version: '3.8'
services:
  teamhack_rest:
    image: innovanon/teamhack-rest
    container_name:  teamhack-rest
    ports:
      - "0.0.0.0:5000:5000/tcp"
    volumes:
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #network_mode:    service:vpn-s1
    #healthcheck:
    ##  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
    #  test: ["CMD-SHELL", "nslookup hackthebox.com 0.0.0.0"]
    #  interval:      1m
    #  timeout:       3s
    #  retries:       10
    depends_on:
      postgres:
        condition: service_healthy
      syslog:
        condition: service_started
        #condition:   service_healthy
      teamhack_dns:
        condition: service_healthy
        
