version: '3.8'
services:
  teamhack_rest:
    image: innovanon/teamhack_rest
    container_name:  teamhack_rest
    ports:
      - "0.0.0.0:5001:5001/tcp"
    volumes:
      - syslog-client:/etc/rsyslog.d:ro
      - teamhack:/var/teamhack/etc:ro
    restart:         always
    #network_mode:    service:vpn-s1
    healthcheck:
      test: ["CMD-SHELL", "python -c 'from requests import post; post(\"0.0.0.0\", data={\"host\":\"hackthebox.com\"})\"'"]
      interval:     10s
      timeout:       5s
      retries:       10
    #  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
    depends_on:
      postgres:
        condition: service_healthy
      syslog:
        condition: service_started
        #condition:   service_healthy
      teamhack_dns:
        condition: service_healthy
        
